package com.example.demo.model;

import java.util.Date;

public class Area {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.ID
     *
     * @mbggenerated Tue Jul 03 15:06:33 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.area_name
     *
     * @mbggenerated Tue Jul 03 15:06:33 CST 2018
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.priority
     *
     * @mbggenerated Tue Jul 03 15:06:33 CST 2018
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.create_time
     *
     * @mbggenerated Tue Jul 03 15:06:33 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.last_edit_time
     *
     * @mbggenerated Tue Jul 03 15:06:33 CST 2018
     */
    private Date lastEditTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.ID
     *
     * @return the value of tb_area.ID
     *
     * @mbggenerated Tue Jul 03 15:06:33 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area.ID
     *
     * @param id the value for tb_area.ID
     *
     * @mbggenerated Tue Jul 03 15:06:33 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.area_name
     *
     * @return the value of tb_area.area_name
     *
     * @mbggenerated Tue Jul 03 15:06:33 CST 2018
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area.area_name
     *
     * @param areaName the value for tb_area.area_name
     *
     * @mbggenerated Tue Jul 03 15:06:33 CST 2018
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.priority
     *
     * @return the value of tb_area.priority
     *
     * @mbggenerated Tue Jul 03 15:06:33 CST 2018
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area.priority
     *
     * @param priority the value for tb_area.priority
     *
     * @mbggenerated Tue Jul 03 15:06:33 CST 2018
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.create_time
     *
     * @return the value of tb_area.create_time
     *
     * @mbggenerated Tue Jul 03 15:06:33 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area.create_time
     *
     * @param createTime the value for tb_area.create_time
     *
     * @mbggenerated Tue Jul 03 15:06:33 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.last_edit_time
     *
     * @return the value of tb_area.last_edit_time
     *
     * @mbggenerated Tue Jul 03 15:06:33 CST 2018
     */
    public Date getLastEditTime() {
        return lastEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area.last_edit_time
     *
     * @param lastEditTime the value for tb_area.last_edit_time
     *
     * @mbggenerated Tue Jul 03 15:06:33 CST 2018
     */
    public void setLastEditTime(Date lastEditTime) {
        this.lastEditTime = lastEditTime;
    }

}