package com.lzhd.core.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Module {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MODULE.ID
     *
     * @mbggenerated Tue Feb 05 20:36:20 CST 2013
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MODULE.NAME
     *
     * @mbggenerated Tue Feb 05 20:36:20 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MODULE.DESCRIPTION
     *
     * @mbggenerated Tue Feb 05 20:36:20 CST 2013
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MODULE.CREATOR
     *
     * @mbggenerated Tue Feb 05 20:36:20 CST 2013
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MODULE.CREATE_TIME
     *
     * @mbggenerated Tue Feb 05 20:36:20 CST 2013
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MODULE.IS_DELETE
     *
     * @mbggenerated Tue Feb 05 20:36:20 CST 2013
     */
    private BigDecimal isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MODULE.ID
     *
     * @return the value of MODULE.ID
     *
     * @mbggenerated Tue Feb 05 20:36:20 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MODULE.ID
     *
     * @param id the value for MODULE.ID
     *
     * @mbggenerated Tue Feb 05 20:36:20 CST 2013
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MODULE.NAME
     *
     * @return the value of MODULE.NAME
     *
     * @mbggenerated Tue Feb 05 20:36:20 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MODULE.NAME
     *
     * @param name the value for MODULE.NAME
     *
     * @mbggenerated Tue Feb 05 20:36:20 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MODULE.DESCRIPTION
     *
     * @return the value of MODULE.DESCRIPTION
     *
     * @mbggenerated Tue Feb 05 20:36:20 CST 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MODULE.DESCRIPTION
     *
     * @param description the value for MODULE.DESCRIPTION
     *
     * @mbggenerated Tue Feb 05 20:36:20 CST 2013
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MODULE.CREATOR
     *
     * @return the value of MODULE.CREATOR
     *
     * @mbggenerated Tue Feb 05 20:36:20 CST 2013
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MODULE.CREATOR
     *
     * @param creator the value for MODULE.CREATOR
     *
     * @mbggenerated Tue Feb 05 20:36:20 CST 2013
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MODULE.CREATE_TIME
     *
     * @return the value of MODULE.CREATE_TIME
     *
     * @mbggenerated Tue Feb 05 20:36:20 CST 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MODULE.CREATE_TIME
     *
     * @param createTime the value for MODULE.CREATE_TIME
     *
     * @mbggenerated Tue Feb 05 20:36:20 CST 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MODULE.IS_DELETE
     *
     * @return the value of MODULE.IS_DELETE
     *
     * @mbggenerated Tue Feb 05 20:36:20 CST 2013
     */
    public BigDecimal getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MODULE.IS_DELETE
     *
     * @param isDelete the value for MODULE.IS_DELETE
     *
     * @mbggenerated Tue Feb 05 20:36:20 CST 2013
     */
    public void setIsDelete(BigDecimal isDelete) {
        this.isDelete = isDelete;
    }
}