package com.lzhd.core.dao;

import com.lzhd.core.entity.Module;

public interface ModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODULE
     *
     * @mbggenerated Tue Feb 05 20:36:20 CST 2013
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODULE
     *
     * @mbggenerated Tue Feb 05 20:36:20 CST 2013
     */
    int insert(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODULE
     *
     * @mbggenerated Tue Feb 05 20:36:20 CST 2013
     */
    int insertSelective(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODULE
     *
     * @mbggenerated Tue Feb 05 20:36:20 CST 2013
     */
    Module selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODULE
     *
     * @mbggenerated Tue Feb 05 20:36:20 CST 2013
     */
    int updateByPrimaryKeySelective(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODULE
     *
     * @mbggenerated Tue Feb 05 20:36:20 CST 2013
     */
    int updateByPrimaryKey(Module record);
}